export const CREATE_ISSUE = "CREATE_ISSUE",
  CREATE_ISSUE_ERROR = "CREATE_ISSUE_ERROR",
  LOAD_ISSUES = "LOAD_ISSUES",
  LOAD_ISSUES_ERROR = "LOAD_ISSUES_ERROR",
  REMOVE_ISSUES = "REMOVE_ISSUES",
  REMOVE_ISSUES_ERROR = "REMOVE_ISSUES_ERROR";
