export const CREATE_ISSUE = "CREATE_ISSUE",
  CREATE_ISSUE_ERROR = "CREATE_ISSUE_ERROR",
  LOAD_ISSUES = "LOAD_ISSUES",
  LOAD_ISSUES_ERROR = "LOAD_ISSUES_ERROR",
  REMOVE_ISSUE = "REMOVE_ISSUE",
  REMOVE_ISSUE_ERROR = "REMOVE_ISSUE_ERROR",
  GET_ISSUE = "GET_ISSUE",
  GET_ISSUE_ERROR = "GET_ISSUE_ERROR",
  UPDATE_ISSUE = "UPDATE_ISSUE",
  UPDATE_ISSUE_ERROR = "UPDATE_ISSUE_ERROR";

export const CHANGE_MODE = "CHANGE_MODE";

export const CHANGE_DATA_SOURCE = "CHANGE_DATA_SOURCE";

export const RESET = "RESET";
